workflows:
  build-ios-simulator:
    name: iOS Simulator Build (for Appetize)
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build iOS for Simulator
        script: flutter build ios --simulator

      - name: Zip the .app for Appetize.io
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/Runner.app.zip
