workflows:
  ios-simulator:
    name: Build for iOS Simulator
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build iOS for simulator
        script: flutter build ios --simulator

      - name: Zip the .app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/Runner.app.zip
